# Generated by Django 5.2 on 2025-05-08 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_id_alter_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='address',
            new_name='nearest_city',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='count',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='latitude',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='longitude',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='orders.order'),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='orders.order')),
            ],
        ),
    ]
