# Generated by Django 5.2 on 2025-05-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_address_orderdetails_nearest_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
