# Generated by Django 5.2 on 2025-05-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_customer_remove_order_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order',
            new_name='order_id',
        ),
    ]
