# Generated by Django 5.2 on 2025-05-08 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_order_orderproduct_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.order'),
            preserve_default=False,
        ),
    ]
