# Generated by Django 5.2 on 2025-05-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderdetails_order_id_orderdetails_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order_id',
            new_name='order',
        ),
    ]
