# Generated by Django 5.2 on 2025-05-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_order_id_orderproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='blockchain_tx_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ipfs_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
