# Generated by Django 5.2 on 2025-05-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='nearest_city',
        ),
    ]
