# Generated by Django 5.2 on 2025-05-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_orderdetails_nearest_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='address',
            field=models.CharField(default='221B', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='city',
            field=models.CharField(default='Colombo', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='first_name',
            field=models.CharField(default='himath', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='last_name',
            field=models.CharField(default='samarakoon', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_number',
            field=models.CharField(default='ORD-524439-4952', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='phone',
            field=models.CharField(default='0772209691', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='state',
            field=models.CharField(default='sd', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='zipcode',
            field=models.CharField(default=10012, max_length=16),
            preserve_default=False,
        ),
    ]
