# Generated by Django 5.2 on 2025-05-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderdetails_address_orderdetails_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='warehouse_name',
            field=models.CharField(default='Colombo First', max_length=255),
            preserve_default=False,
        ),
    ]
