# Generated by Django 5.2 on 2025-05-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderdetails_warehouse_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='blockchain_tx_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ipfs_hash',
        ),
    ]
