services:
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs-node
    ports:
      - "4001:4001"   # Swarm
      - "5001:5001"   # API
      - "8989:8080"   # Gateway
    volumes:
      - ipfs_data:/data/ipfs
      - ipfs_staging:/export
    restart: unless-stopped
    networks:
      - scms

volumes:
  ipfs_data:
  ipfs_staging:

networks:
  scms:
    external: true
    name: scms-network