# Generated by Django 5.2 on 2025-05-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('expected_delivery_date', models.DateTimeField()),
                ('product_id', models.IntegerField()),
                ('count', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received')], max_length=10)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('warehouse_id', models.IntegerField()),
                ('unit_price', models.FloatField()),
            ],
        ),
    ]
