# Generated by Django 5.2 on 2025-05-08 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierrequest',
            name='is_defective',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierrequest',
            name='quality',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='supplierrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('received', 'Received'), ('returned', 'Returned'), ('rejected', 'Rejected')], max_length=10),
        ),
    ]
